"""Generated byte fixtures for the dependency-free image inspector."""

from __future__ import annotations

import struct
import zlib

import pytest

from nabiz.console.photo_image import (
    MAX_PHOTO_BYTES,
    MAX_PHOTO_EDGE,
    PhotoRejected,
    clean_photo,
    photo_dimensions,
    photo_kind,
    strip_photo_metadata,
)


def jpeg(width: int = 4, height: int = 3) -> bytes:
    app_data = b"Exif\x00GPSprivate"
    app = b"\xff\xe1" + struct.pack(">H", len(app_data) + 2) + app_data
    frame = b"\xff\xc0\x00\x0b" + bytes((8,)) + struct.pack(">HH", height, width) + bytes((1, 1, 0x11, 0))
    scan = b"\xff\xda\x00\x08\x01\x01\x00\x00\x3f\x00\x12\x34\xff\xd9"
    return b"\xff\xd8" + app + frame + scan


def png_chunk(kind: bytes, content: bytes) -> bytes:
    checksum = zlib.crc32(kind + content) & 0xFFFFFFFF
    return struct.pack(">I", len(content)) + kind + content + struct.pack(">I", checksum)


def png(width: int = 4, height: int = 3) -> bytes:
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    pixels = zlib.compress(b"\x00" + bytes((1, 2, 3)) * width)
    return b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", header) + png_chunk(b"eXIf", b"GPS private") \
        + png_chunk(b"tEXt", b"note\x00private") + png_chunk(b"IDAT", pixels) + png_chunk(b"IEND", b"")


def webp_chunk(kind: bytes, content: bytes) -> bytes:
    chunk = kind + struct.pack("<I", len(content)) + content
    return chunk + (b"\x00" if len(content) & 1 else b"")


def webp(width: int = 4, height: int = 3, *, animated: bool = False) -> bytes:
    flags = 0x02 if animated else 0x2C
    extended = bytes((flags, 0, 0, 0)) + (width - 1).to_bytes(3, "little") + (height - 1).to_bytes(3, "little")
    packed = (((height - 1) & 0x03) << 6) | (((width - 1) >> 8) & 0x3F)
    lossless = bytes((0x2F, width - 1, packed, (height - 1) >> 2, 0, 0x44))
    body = webp_chunk(b"VP8X", extended) + webp_chunk(b"EXIF", b"Exif\x00GPS")
    if animated:
        body += webp_chunk(b"ANIM", b"\x00" * 6)
    body += webp_chunk(b"VP8L", lossless)
    return b"RIFF" + struct.pack("<I", len(body) + 4) + b"WEBP" + body


def png_idat(data: bytes) -> bytes:
    start = data.index(b"IDAT") - 4
    size = int.from_bytes(data[start : start + 4], "big")
    return data[start : start + size + 12]


@pytest.mark.parametrize(
    ("data", "kind", "dims"),
    [(jpeg(), "jpeg", (4, 3)), (png(), "png", (4, 3)), (webp(), "webp", (4, 3))],
)
def test_magic_dimensions_and_cleaned_metadata(data: bytes, kind: str, dims: tuple[int, int]) -> None:
    assert photo_kind(data) == kind
    assert photo_dimensions(data, kind) == dims
    cleaned = clean_photo(data)
    assert cleaned.kind == kind
    assert (cleaned.width, cleaned.height) == dims
    assert photo_dimensions(cleaned.data, kind) == dims
    assert not any(marker in cleaned.data for marker in (b"Exif", b"GPS", b"tEXt", b"eXIf", b"XMP"))


def test_cleaning_preserves_encoded_image_payloads() -> None:
    jpeg_data = jpeg()
    jpeg_clean = strip_photo_metadata(jpeg_data, "jpeg")
    assert jpeg_clean[jpeg_clean.index(b"\xff\xda") :] == jpeg_data[jpeg_data.index(b"\xff\xda") :]

    png_data = png()
    png_clean = strip_photo_metadata(png_data, "png")
    assert png_idat(png_data) in png_clean

    webp_data = webp()
    webp_clean = strip_photo_metadata(webp_data, "webp")
    assert webp_chunk(b"VP8L", bytes((0x2F, 3, 0x80, 0, 0, 0x44))) in webp_clean
    assert webp_clean[20] & 0x2C == 0


@pytest.mark.parametrize("data", [b"", b"GIF89a", b"<svg></svg>", b"\x00\x00\x00\x00ftypheic", b"BMxxxx", b"\xff\xd8"])
def test_unsupported_and_short_signatures_are_rejected(data: bytes) -> None:
    assert photo_kind(data) is None
    with pytest.raises(PhotoRejected) as rejected:
        clean_photo(data)
    assert rejected.value.code == "bad_type"


def test_malformed_and_animated_images_are_rejected() -> None:
    with pytest.raises(PhotoRejected, match="malformed"):
        clean_photo(jpeg()[:-2])
    with pytest.raises(PhotoRejected, match="malformed"):
        clean_photo(webp(animated=True))
    with pytest.raises(PhotoRejected, match="malformed"):
        clean_photo(png()[:-2])


def test_size_and_long_edge_limits_are_server_enforced() -> None:
    assert MAX_PHOTO_BYTES == 2 * 1024 * 1024
    assert MAX_PHOTO_EDGE == 1600
    with pytest.raises(PhotoRejected, match="too_large"):
        clean_photo(jpeg() + b"x" * (MAX_PHOTO_BYTES + 1 - len(jpeg())))
    with pytest.raises(PhotoRejected, match="too_many_pixels"):
        clean_photo(jpeg(width=1601))
