#!/usr/bin/env python3
"""Build the page's icons from the official Tabler Icons tarball: an inline sprite, icons.svg, a favicon.

Tabler Icons 3.48.0, outline set, MIT (docs/design/DESIGN.md §5). One family, nothing hand-drawn, no
Unicode glyph used as an icon. The tarball is the one npm publishes, checked against the integrity
hash npm reports for this version before anything is read from it, so the glyphs are the release's
and nobody's redrawing.

Outputs, each marked as generated:

* ``index.html``: between ``<!-- icons:start -->`` and ``<!-- icons:end -->`` in ``<body>``, a hidden
  sprite of the ``INLINE`` glyphs, the ones the static markup uses, so the first view needs no request
  for them; and between the same markers in ``<head>``, the favicon: the ``activity`` glyph on a
  rounded square in the page's primary button colours, light and dark, read from ``css/tokens.css``
  (a favicon cannot read CSS custom properties, so the values are copied here, not typed).
* ``static/icons.svg``: the ``EXTERNAL`` glyphs, which only answers rendered by script use; same
  origin, cached, fetched once when the first answer needs one.
* ``static/icons.LICENSE.txt``: the package's MIT licence, verbatim, next to the glyphs it covers.

Each glyph becomes ``<symbol id="i-<name>" viewBox="0 0 24 24">`` with the wrapper, size, class,
stroke attributes and Tabler's invisible bounding path removed: one CSS rule (``.icon`` in
``css/base.css``) sets every stroke, so icons and the data pen share one weight. ``js/icons.js``
decides inline or external by the same ``INLINE`` list (``tests/test_web_assets.py`` holds them equal).

Usage::

    curl -sSfLO https://registry.npmjs.org/@tabler/icons/-/icons-3.48.0.tgz   # 1,257,051 B
    .venv/bin/python scripts/design/build_icon_sprite.py icons-3.48.0.tgz

Standard library only. The download is the only network step, and it is yours to run.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import pathlib
import re
import sys
import tarfile
import urllib.parse

ROOT = pathlib.Path(__file__).resolve().parents[2]
STATIC = ROOT / "src/nabiz/web/static"
VERSION = "3.48.0"
#: ``npm view @tabler/icons@3.48.0 dist.integrity``, read 2026-09-23.
INTEGRITY = "sha512-lQk06gVHNVBnJp0UOgtth54mcZBJM7rdYKsAxKOProj1bbSAx+/xiuOWfHlyvgdL3M+Y+I0HINrjHa3ygp8eXQ=="

#: The glyphs the static markup uses (spec §6): kept in the page, so the first view fetches none.
INLINE = (
    "search", "arrow-right", "parking", "bus", "train", "wind", "traffic-lights", "device-desktop", "sun", "moon",
    "info-circle", "refresh", "clock", "history", "clock-exclamation", "clock-question", "bus-stop", "route",
    "external-link",
)
#: The glyphs only script-rendered answers use (spec §6).
EXTERNAL = (
    "car", "walk", "map-pin", "map", "arrow-narrow-right", "chevron-right", "alert-triangle", "circle-check",
    "trending-up", "trending-down", "equal", "elevator", "escalator", "toilet-paper", "baby-carriage",
    "building-mosque", "wheelchair", "antenna-bars-5", "antenna-bars-3", "antenna-bars-1", "bolt", "armchair",
    "search-off", "map-off", "list-details", "bell", "shield-lock", "cloud-off", "wifi-off", "gauge", "clock-pause",
    "arrows-exchange",
)
FAVICON = "activity"
#: The inline sprite is a zero-size, hidden holder of symbols: without CSS it still takes no space.
INLINE_ATTRIBUTES = 'class="sprite" xmlns="http://www.w3.org/2000/svg" width="0" height="0" aria-hidden="true" focusable="false"'
BLOCK = re.compile(r"<!-- icons:start -->.*?<!-- icons:end -->", re.S)
HEADER = (f"Tabler Icons {VERSION}, outline set, MIT licence, Copyright (c) 2020-2026 Paweł Kuna: /icons.LICENSE.txt. "
          "Generated by scripts/design/build_icon_sprite.py; do not edit by hand.")
#: Favicon colours: the primary button in each theme (--primary on --on-primary), by ramp step.
FAVICON_TOKENS = {"light": ("primary-700", "neutral-0"), "dark": ("primary-500", "neutral-1000")}


def verify(tarball: pathlib.Path) -> None:
    algorithm, _, expected = INTEGRITY.partition("-")
    digest = base64.b64encode(hashlib.new(algorithm, tarball.read_bytes()).digest()).decode()
    if digest != expected:
        raise SystemExit(f"{tarball.name} does not match the integrity npm publishes for @tabler/icons@{VERSION}")


def read_glyphs(tarball: pathlib.Path, names: tuple[str, ...]) -> tuple[dict[str, str], str]:
    """The outline SVG of each name, and the package licence text."""
    with tarfile.open(tarball, "r:gz") as tar:
        def text(member: str) -> str:
            handle = tar.extractfile(member)
            if handle is None:
                raise SystemExit(f"{member} is not a file in the tarball")
            return handle.read().decode("utf-8")

        return {name: text(f"package/icons/outline/{name}.svg") for name in names}, text("package/LICENSE")


def shapes(svg: str) -> str:
    """The drawing inside one Tabler SVG: no wrapper, no invisible bounding path, whitespace collapsed."""
    inner = re.search(r"<svg\b[^>]*>(.*)</svg>", svg, re.S)
    if inner is None:
        raise ValueError("not an SVG")
    body = re.sub(r'<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*/>', "", inner.group(1))
    body = re.sub(r"\s*/>", "/>", re.sub(r"\s+", " ", body)).strip()
    return re.sub(r">\s+<", "><", body)


def symbol(name: str, svg: str) -> str:
    return f'<symbol id="i-{name}" viewBox="0 0 24 24">{shapes(svg)}</symbol>'


def token_values(tokens_css: str) -> dict[str, str]:
    """Ramp values from the light :root block of tokens.css (the ramps do not change with the theme)."""
    return dict(re.findall(r"--((?:primary|neutral)-\d+):\s*(#[0-9a-f]{6});", tokens_css))


def favicon(svg: str, tokens: dict[str, str]) -> str:
    """The favicon link: the glyph on a rounded square, with its own dark-scheme colours."""
    (fill, ink), (dark_fill, dark_ink) = ([tokens[t] for t in FAVICON_TOKENS[theme]] for theme in ("light", "dark"))
    drawing = shapes(svg).replace("<path ", "<path fill='none' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' ")
    image = (
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='-3 -3 30 30'>"
        f"<style>rect{{fill:{fill}}}path{{stroke:{ink}}}"
        f"@media (prefers-color-scheme:dark){{rect{{fill:{dark_fill}}}path{{stroke:{dark_ink}}}}}</style>"
        f"<rect x='-3' y='-3' width='30' height='30' rx='7'/>{drawing.replace(chr(34), chr(39))}</svg>"
    )
    # Spaces and single quotes may stay: the value sits in a double-quoted attribute.
    href = "data:image/svg+xml," + urllib.parse.quote(image, safe=" /:=,;()-.'")
    return f'<link rel="icon" href="{href}">'


def sprite(glyphs: dict[str, str], names: tuple[str, ...], attributes: str) -> str:
    rows = "\n".join(symbol(name, glyphs[name]) for name in names)
    return f"<svg {attributes}>\n<!-- {HEADER} -->\n{rows}\n</svg>"


def write_page(index: pathlib.Path, head_block: str, body_block: str) -> None:
    """Replace the generated block in <head> and the one in <body>, leaving everything else as it is."""
    html = index.read_text(encoding="utf-8")
    head, sep, body = html.partition("</head>")
    for part in (head, body):
        if len(BLOCK.findall(part)) != 1:
            raise SystemExit(f"{index.name} needs exactly one icons:start/icons:end block in <head> and one in <body>")
    wrap = "<!-- icons:start -->\n{}\n<!-- icons:end -->".format
    head = BLOCK.sub(lambda _m: wrap(head_block), head)
    body = BLOCK.sub(lambda _m: wrap(body_block), body)
    index.write_text(head + sep + body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("tarball", type=pathlib.Path, help=f"icons-{VERSION}.tgz from registry.npmjs.org")
    parser.add_argument("--static", type=pathlib.Path, default=STATIC)
    args = parser.parse_args(argv)
    verify(args.tarball)
    glyphs, licence = read_glyphs(args.tarball, (*INLINE, *EXTERNAL, FAVICON))
    tokens = token_values((args.static / "css/tokens.css").read_text(encoding="utf-8"))
    inline = sprite(glyphs, INLINE, INLINE_ATTRIBUTES)
    write_page(args.static / "index.html", favicon(glyphs[FAVICON], tokens), inline)
    external = sprite(glyphs, EXTERNAL, 'xmlns="http://www.w3.org/2000/svg"')
    (args.static / "icons.svg").write_text(external + "\n", encoding="utf-8")
    (args.static / "icons.LICENSE.txt").write_text(licence, encoding="utf-8")
    print(f"{len(INLINE)} inline, {len(EXTERNAL)} in icons.svg, favicon {FAVICON}; "
          f"icons.svg {len(external.encode()) + 1:,} B, inline sprite {len(inline.encode()):,} B")
    return 0


if __name__ == "__main__":
    sys.exit(main())
