"""The 112 card's fixed text in every card language: the one source, with no model behind it.

The page speaks Turkish and English (DECISIONS #35); only the emergency card speaks the languages of
the visitors İstanbul receives most (DECISIONS #37). ``static/js/emergency_text.js`` is a copy of these
values, held equal by ``tests/test_emergency_multilingual.py``: change both or the test fails.

Every translation except Turkish and English is the project's own and unchecked by a native reader, so
the card shows :data:`UNVERIFIED_LABEL` beside it. The Turkish block (:data:`TR_BLOCK`) is on every card:
the person can show it to anyone nearby. Phone numbers: 112 on every card; İGDAŞ's 187 only for a gas
leak (DECISIONS #36); 153 is the city's non-emergency line.
"""

from __future__ import annotations

#: Languages whose text a native reader has checked: no "unverified" label.
REVIEWED_LANGS = ("tr", "en")
#: Right-to-left card languages: the card (not the page) gets ``dir="rtl"``.
RTL_LANGS = ("ar", "fa")
UNVERIFIED_LABEL = "otomatik çeviri · doğrulanmadı"
#: The large Turkish block under every card; ``gas`` only on a gas leak.
TR_BLOCK = {"plea": "LÜTFEN YARDIM EDİN · 112'Yİ ARAYIN", "gas": "GAZ KAÇAĞI · 187"}

CARD_TEXT: dict[str, dict[str, str]] = {
    "tr": {
        "title": "Hemen 112'yi arayın",
        "show": "Bu ekranı yanınızdaki birine gösterin.",
        "note": "Sohbeti durdurdum. Bu site yardım çağıramaz; aramayı siz yapın.",
        "live": "Acil durum olabilir. 112'yi arayın.",
        "call": "112'yi ara",
        "gas": "Gaz kaçağı: İGDAŞ 187 Doğal Gaz Acil Hattı",
        "locate": "Konumumu göster",
        "copy": "Kopyala",
        "grow": "Türkçe yazıyı büyüt",
        "line153": "153 Çözüm Merkezi (acil olmayan konular)",
        "back": "Acil değil, geri dön",
        "foot": "Resmî İBB hizmeti değildir. Nabız bağımsız bir projedir. Konumunuz yalnız bu cihazda kalır.",
        "waiting": "Konum alınıyor.",
        "shown": "Konumunuz: {coords}. Bu sayıları 112'ye okuyabilirsiniz.",
        "copied": "Panoya kopyalandı: {coords}.",
        "copyfail": "Kopyalanamadı. Sayıları ekrandan okuyun: {coords}.",
        "denied": "Konum alınamadı. Adresinizi 112'ye söyleyin.",
    },
    "en": {
        "title": "Call 112 now",
        "show": "Show this screen to someone near you.",
        "note": "I stopped the chat. This site cannot call for help; make the call yourself.",
        "live": "This may be an emergency. Call 112.",
        "call": "Call 112",
        "gas": "Gas leak: İGDAŞ 187 natural gas emergency line",
        "locate": "Show my location",
        "copy": "Copy",
        "grow": "Show the Turkish text larger",
        "line153": "153 Solution Centre (non-emergency matters)",
        "back": "Not an emergency, go back",
        "foot": "Not an official İBB service. Nabız is an independent project. Your location stays on this device only.",
        "waiting": "Getting your location.",
        "shown": "Your location: {coords}. You can read these numbers to 112.",
        "copied": "Copied to the clipboard: {coords}.",
        "copyfail": "Could not copy. Read the numbers from the screen: {coords}.",
        "denied": "Could not get your location. Tell 112 your address.",
    },
    "ar": {
        "title": "اتصل بالرقم 112 الآن",
        "show": "أظهر هذه الشاشة لشخص قريب منك.",
        "note": "أوقفت المحادثة. هذا الموقع لا يستطيع طلب المساعدة؛ اتصل أنت.",
        "live": "قد تكون هذه حالة طارئة. اتصل بالرقم 112.",
        "call": "اتصل بالرقم 112",
        "gas": "تسرب غاز: İGDAŞ 187، خط طوارئ الغاز",
        "locate": "أظهر موقعي",
        "copy": "نسخ",
        "grow": "كبّر النص التركي",
        "line153": "153 مركز خدمات البلدية (لغير الطوارئ)",
        "back": "ليست حالة طارئة، رجوع",
        "foot": "ليست خدمة رسمية من İBB. Nabız مشروع مستقل. يبقى موقعك على هذا الجهاز فقط.",
        "waiting": "جار تحديد موقعك.",
        "shown": "موقعك: {coords}. اقرأ هذه الأرقام لموظف 112.",
        "copied": "تم النسخ: {coords}.",
        "copyfail": "تعذر النسخ. اقرأ الأرقام من الشاشة: {coords}.",
        "denied": "تعذر تحديد الموقع. أخبر 112 بعنوانك.",
    },
    "ru": {
        "title": "Срочно звоните 112",
        "show": "Покажите этот экран человеку рядом.",
        "note": "Чат остановлен. Этот сайт не может вызвать помощь; позвоните сами.",
        "live": "Возможно, это экстренный случай. Звоните 112.",
        "call": "Позвонить 112",
        "gas": "Утечка газа: İGDAŞ 187, аварийная газовая служба",
        "locate": "Показать моё местоположение",
        "copy": "Копировать",
        "grow": "Увеличить текст на турецком",
        "line153": "153 Городская справочная служба (не экстренно)",
        "back": "Не экстренно, назад",
        "foot": "Это не официальная служба İBB. Nabız является независимым проектом. "
        "Ваше местоположение остаётся только на этом устройстве.",
        "waiting": "Определяем местоположение.",
        "shown": "Ваше местоположение: {coords}. Продиктуйте эти цифры службе 112.",
        "copied": "Скопировано: {coords}.",
        "copyfail": "Не удалось скопировать. Прочитайте цифры с экрана: {coords}.",
        "denied": "Не удалось определить местоположение. Назовите свой адрес службе 112.",
    },
    "de": {
        "title": "Rufen Sie sofort 112 an",
        "show": "Zeigen Sie diesen Bildschirm einer Person in Ihrer Nähe.",
        "note": "Der Chat ist gestoppt. Diese Seite kann keine Hilfe rufen; rufen Sie selbst an.",
        "live": "Das kann ein Notfall sein. Rufen Sie 112 an.",
        "call": "112 anrufen",
        "gas": "Gasleck: İGDAŞ 187, Gas-Notruf",
        "locate": "Meinen Standort zeigen",
        "copy": "Kopieren",
        "grow": "Türkischen Text groß zeigen",
        "line153": "153 Bürgerservice der Stadt (kein Notfall)",
        "back": "Kein Notfall, zurück",
        "foot": "Kein offizieller Dienst der İBB. Nabız ist ein unabhängiges Projekt. Ihr Standort bleibt nur auf diesem Gerät.",
        "waiting": "Standort wird ermittelt.",
        "shown": "Ihr Standort: {coords}. Lesen Sie diese Zahlen der 112 vor.",
        "copied": "In die Zwischenablage kopiert: {coords}.",
        "copyfail": "Kopieren nicht möglich. Lesen Sie die Zahlen vom Bildschirm ab: {coords}.",
        "denied": "Standort nicht verfügbar. Nennen Sie der 112 Ihre Adresse.",
    },
    "fa": {
        "title": "همین حالا با 112 تماس بگیرید",
        "show": "این صفحه را به یک نفر در نزدیکی خود نشان دهید.",
        "note": "گفتگو را متوقف کردم. این سایت نمی‌تواند کمک خبر کند؛ خودتان تماس بگیرید.",
        "live": "ممکن است وضعیت اضطراری باشد. با 112 تماس بگیرید.",
        "call": "تماس با 112",
        "gas": "نشت گاز: İGDAŞ 187، خط اضطراری گاز",
        "locate": "نمایش موقعیت من",
        "copy": "کپی",
        "grow": "بزرگ کردن متن ترکی",
        "line153": "153 مرکز خدمات شهرداری (غیر اضطراری)",
        "back": "اضطراری نیست، بازگشت",
        "foot": "این خدمت رسمی İBB نیست. Nabız یک پروژه مستقل است. موقعیت شما فقط روی همین دستگاه می‌ماند.",
        "waiting": "در حال یافتن موقعیت شما.",
        "shown": "موقعیت شما: {coords}. این اعداد را برای 112 بخوانید.",
        "copied": "کپی شد: {coords}.",
        "copyfail": "کپی نشد. اعداد را از روی صفحه بخوانید: {coords}.",
        "denied": "موقعیت پیدا نشد. نشانی خود را به 112 بگویید.",
    },
    "es": {
        "title": "Llame al 112 ahora",
        "show": "Muestre esta pantalla a alguien cerca de usted.",
        "note": "He detenido el chat. Este sitio no puede pedir ayuda; llame usted.",
        "live": "Puede ser una emergencia. Llame al 112.",
        "call": "Llamar al 112",
        "gas": "Fuga de gas: İGDAŞ 187, urgencias de gas",
        "locate": "Mostrar mi ubicación",
        "copy": "Copiar",
        "grow": "Ampliar el texto en turco",
        "line153": "153 Centro de atención municipal (no urgente)",
        "back": "No es una emergencia, volver",
        "foot": "No es un servicio oficial de İBB. Nabız es un proyecto independiente. "
        "Su ubicación se queda en este dispositivo.",
        "waiting": "Obteniendo su ubicación.",
        "shown": "Su ubicación: {coords}. Lea estos números al 112.",
        "copied": "Copiado: {coords}.",
        "copyfail": "No se pudo copiar. Lea los números en la pantalla: {coords}.",
        "denied": "No se pudo obtener la ubicación. Diga su dirección al 112.",
    },
    "fr": {
        "title": "Appelez le 112 maintenant",
        "show": "Montrez cet écran à une personne près de vous.",
        "note": "J'ai arrêté la conversation. Ce site ne peut pas appeler les secours. Appelez vous-même.",
        "live": "C'est peut-être une urgence. Appelez le 112.",
        "call": "Appeler le 112",
        "gas": "Fuite de gaz : İGDAŞ 187, urgence gaz",
        "locate": "Afficher ma position",
        "copy": "Copier",
        "grow": "Agrandir le texte turc",
        "line153": "153 Centre de services de la ville (hors urgence)",
        "back": "Pas une urgence, retour",
        "foot": "Service non officiel de l'İBB. Nabız est un projet indépendant. Votre position reste sur cet appareil.",
        "waiting": "Recherche de votre position.",
        "shown": "Votre position : {coords}. Lisez ces chiffres au 112.",
        "copied": "Copié : {coords}.",
        "copyfail": "Copie impossible. Lisez les chiffres à l'écran : {coords}.",
        "denied": "Position introuvable. Donnez votre adresse au 112.",
    },
    "it": {
        "title": "Chiami subito il 112",
        "show": "Mostri questo schermo a una persona vicina.",
        "note": "Ho fermato la chat. Questo sito non può chiamare i soccorsi; chiami lei.",
        "live": "Potrebbe essere un'emergenza. Chiami il 112.",
        "call": "Chiama il 112",
        "gas": "Fuga di gas: İGDAŞ 187, emergenza gas",
        "locate": "Mostra la mia posizione",
        "copy": "Copia",
        "grow": "Ingrandisci il testo turco",
        "line153": "153 Centro servizi del comune (non urgente)",
        "back": "Non è un'emergenza, torna indietro",
        "foot": "Non è un servizio ufficiale İBB. Nabız è un progetto indipendente. "
        "La sua posizione resta su questo dispositivo.",
        "waiting": "Ricerca della posizione.",
        "shown": "La sua posizione: {coords}. Legga questi numeri al 112.",
        "copied": "Copiato: {coords}.",
        "copyfail": "Impossibile copiare. Legga i numeri sullo schermo: {coords}.",
        "denied": "Posizione non disponibile. Dica il suo indirizzo al 112.",
    },
    "uk": {
        "title": "Негайно телефонуйте 112",
        "show": "Покажіть цей екран людині поруч.",
        "note": "Чат зупинено. Цей сайт не може викликати допомогу; зателефонуйте самі.",
        "live": "Можливо, це екстрена ситуація. Телефонуйте 112.",
        "call": "Зателефонувати 112",
        "gas": "Витік газу: İGDAŞ 187, аварійна газова служба",
        "locate": "Показати моє місцезнаходження",
        "copy": "Копіювати",
        "grow": "Збільшити текст турецькою",
        "line153": "153 Міська довідкова служба (не екстрено)",
        "back": "Не екстрено, назад",
        "foot": "Це не офіційна служба İBB. Nabız є незалежним проєктом. "
        "Ваше місцезнаходження залишається лише на цьому пристрої.",
        "waiting": "Визначаємо місцезнаходження.",
        "shown": "Ваше місцезнаходження: {coords}. Продиктуйте ці цифри службі 112.",
        "copied": "Скопійовано: {coords}.",
        "copyfail": "Не вдалося скопіювати. Прочитайте цифри з екрана: {coords}.",
        "denied": "Не вдалося визначити місцезнаходження. Назвіть свою адресу службі 112.",
    },
}
#: The card languages, Turkish first; any other code falls back to Turkish on the page.
CARD_LANGS = tuple(CARD_TEXT)
