"""Turn a place name a person typed into coordinates.

Deliberately a local CSV lookup rather than a geocoding API call. Three reasons:

* every journey starts with this step, so a network hop here would double the latency of
  every answer and burn the Azure Maps free transaction budget,
* the gazetteer is built from İBB's own data (metro stations, air-quality stations,
  İSPARK district centroids) plus a short hand-written landmark list, so it resolves the
  names Istanbulites actually say,
* it works offline, which keeps the test suite and the demo reproducible.

``data/reference/places.csv`` is regenerated by ``scripts/build_places.py``. Azure Maps
Search stays available as an optional fallback for names the gazetteer misses.
"""

from __future__ import annotations

import csv
import logging
import unicodedata
from dataclasses import dataclass
from functools import lru_cache

from ibb_mcp.config import Settings
from ibb_mcp.models import haversine_km

log = logging.getLogger("ibb_mcp.places")

#: Turkish characters that must fold onto their ASCII neighbours so that "sisli" finds
#: "Şişli" and "kadikoy" finds "Kadıköy". str.casefold() alone does not do this, and the
#: dotted/dotless i pair breaks naive lowercasing.
_TR_FOLD = str.maketrans(
    {
        "İ": "i", "I": "i", "ı": "i", "Ş": "s", "ş": "s", "Ğ": "g", "ğ": "g",
        "Ü": "u", "ü": "u", "Ö": "o", "ö": "o", "Ç": "c", "ç": "c", "Â": "a", "â": "a",
    }
)


def normalize_tr(text: str | None) -> str:
    """Fold Turkish text for comparison: case, diacritics and punctuation removed."""
    if not text:
        return ""
    folded = text.translate(_TR_FOLD).casefold()
    decomposed = unicodedata.normalize("NFKD", folded)
    stripped = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    return " ".join("".join(ch if ch.isalnum() else " " for ch in stripped).split())


@dataclass(frozen=True)
class Place:
    name: str
    lat: float
    lon: float
    kind: str
    district: str = ""
    distance_km: float | None = None

    @property
    def label(self) -> str:
        if self.district and normalize_tr(self.district) != normalize_tr(self.name):
            return f"{self.name} ({self.district})"
        return self.name


#: Common spoken forms that do not appear verbatim in the gazetteer.
_ALIASES = {
    "taksim": "taksim meydani",
    "kadikoy": "kadikoy iskele",
    "besiktas": "besiktas iskele",
    "uskudar": "uskudar iskele",
    "sultan ahmet": "sultanahmet",
    "galata": "galata kulesi",
    "bakirkoy": "bakirkoy carsi",
    "4 levent": "levent",
    "dorduncu levent": "levent",
}


class PlaceIndex:
    """In-memory gazetteer loaded from ``places.csv``."""

    def __init__(self, places: list[Place]) -> None:
        self.places = places
        self._by_norm: dict[str, list[Place]] = {}
        for place in places:
            self._by_norm.setdefault(normalize_tr(place.name), []).append(place)

    # -- construction ------------------------------------------------------------
    @classmethod
    def load(cls, settings: Settings | None = None) -> PlaceIndex:
        settings = settings or Settings.from_env()
        path = settings.places_csv
        if not path.exists():
            log.warning("places.csv not found at %s; place lookup will return nothing", path)
            return cls([])
        places: list[Place] = []
        with path.open(encoding="utf-8", newline="") as fh:
            for row in csv.DictReader(fh):
                try:
                    places.append(
                        Place(
                            name=row["name"].strip(),
                            lat=float(row["lat"]),
                            lon=float(row["lon"]),
                            kind=row.get("kind", "").strip(),
                            district=(row.get("district") or "").strip(),
                        )
                    )
                except (KeyError, ValueError):
                    continue
        log.info("loaded %d places from %s", len(places), path)
        return cls(places)

    # -- queries -----------------------------------------------------------------
    def resolve(self, query: str, limit: int = 5) -> list[Place]:
        """Best matches for a free-text place name, most confident first.

        Ranking is exact match, then alias, then prefix, then substring, then token
        overlap. Landmarks and district centroids outrank metro stations at equal score
        because a person saying "Kadıköy" means the neighbourhood, not one platform.
        """
        needle = normalize_tr(query)
        if not needle:
            return []
        needle = _ALIASES.get(needle, needle)

        scored: list[tuple[float, Place]] = []
        for place in self.places:
            name = normalize_tr(place.name)
            if name == needle:
                score = 100.0
            elif name.startswith(needle):
                score = 80.0 - min(20.0, len(name) - len(needle))
            elif needle in name:
                score = 60.0 - min(20.0, len(name) - len(needle))
            else:
                needle_tokens, name_tokens = set(needle.split()), set(name.split())
                if not (needle_tokens & name_tokens):
                    continue
                score = 30.0 * len(needle_tokens & name_tokens) / max(1, len(needle_tokens))
            score += {"landmark": 6.0, "district": 4.0, "aq_station": 1.0}.get(place.kind, 0.0)
            scored.append((score, place))

        scored.sort(key=lambda item: (-item[0], len(item[1].name)))
        return [place for _, place in scored[:limit]]

    def resolve_one(self, query: str) -> Place | None:
        matches = self.resolve(query, limit=1)
        return matches[0] if matches else None

    def nearest(self, lat: float, lon: float, *, kind: str | None = None, limit: int = 3) -> list[Place]:
        """Named places closest to a coordinate, used to describe a position back to the user."""
        candidates = [p for p in self.places if kind is None or p.kind == kind]
        ranked = sorted(
            (
                Place(p.name, p.lat, p.lon, p.kind, p.district, round(haversine_km(lat, lon, p.lat, p.lon), 3))
                for p in candidates
            ),
            key=lambda p: p.distance_km or 0.0,
        )
        return ranked[:limit]

    def stats(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for place in self.places:
            counts[place.kind] = counts.get(place.kind, 0) + 1
        counts["total"] = len(self.places)
        return counts


@lru_cache(maxsize=4)
def _cached_index(places_csv: str) -> PlaceIndex:
    return PlaceIndex.load(Settings(places_csv=__import__("pathlib").Path(places_csv)))


def get_place_index(settings: Settings | None = None) -> PlaceIndex:
    """Memoised accessor so the CSV is parsed once per process."""
    settings = settings or Settings.from_env()
    return _cached_index(str(settings.places_csv))
